all:
	cd ArduinoIDEExample && $(MAKE) all
	cd SmallHardwareExample && $(MAKE) all
	cd SimpleMemoryGetSet && $(MAKE) all

clean:
	cd ArduinoIDEExample && $(MAKE) clean
	cd SmallHardwareExample && $(MAKE) clean
	cd SimpleMemoryGetSet && $(MAKE) clean

test:


.PHONY: all clean test
